### ISSUE TITLE
Error Generating Metadata with EFCore and Identity

### ISSUE THREAD

**Issue by jcsilvers** [Breeze/breeze.sharp#34]
When I attempt to generate metadata I get the below error. I am using EF Core with identity

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Breeze.Persistence.EFCore.MetadataBuilder.BuildAssocName(INavigation prop) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 138
   at Breeze.Persistence.EFCore.MetadataBuilder.CreateNavProperty(INavigation p) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 128
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Breeze.Persistence.EFCore.MetadataBuilder.CreateMetaType(IEntityType et, Dictionary`2 dbSetMap) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 89
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Breeze.Persistence.EFCore.MetadataBuilder.GetMetadataFromContext(DbContext dbContext) in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\MetadataBuilder.cs:line 21
   at Breeze.Persistence.EFCore.EFPersistenceManager`1.BuildJsonMetadata() in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence.EFCore\EFPersistenceManager.cs:line 109
   at Breeze.Persistence.PersistenceManager.Metadata() in C:\git\Breeze\breeze.server.net\AspNetCore\Breeze.Persistence\PersistenceManager.cs:line 34
   at MITSBusinessLib.Repositories.EventOrganizerRepo.MetaData() in C:\Users\Jason\Documents\MITSWebApp\MITSBusinessLib\Repositories\EventOrganizerRepo.cs:line 28
   at MITSWebServices.Controllers.EventOrganizerController.Metadata() in C:\Users\Jason\Documents\MITSWebApp\MITSWebServices\Controllers\EventOrganizerController.cs:line 29
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

This is my Context

```C#
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using MITSDataLib.Models;
using System;
using System.Collections.Generic;
using System.Text;

namespace MITSDataLib.Contexts
{
    public class MITSContext : IdentityDbContext<User>
    {

        public MITSContext(DbContextOptions<MITSContext> options): base(options)
        {
            //Do I need these with EF CORE?
            //Configuration.ProxyCreationEnabled = false;
            //Configuration.LazyLoadingEnabled = false;
        }
                
        public DbSet<WildApricotEvent> WaEvents { get; set; }
        public DbSet<WildApricotRegistrationType> WaRegistrationTypes { get; set; }
        public DbSet<Tag> Tags { get; set; }
        public DbSet<Speaker> Speakers { get; set; }
        public DbSet<Section> Sections { get; set; }
        public DbSet<Event> Events { get; set; }
        public DbSet<Day> Days { get; set; }
        public DbSet<Person> People { get; set; }

        
    }
}
```

**Comment by jcsilvers** [comment]
I am sorry. I think I posted this in the wrong repo.
