### ISSUE TITLE
LoadNavigationProperty on modified entity causes a crash (v0.7.0)

### ISSUE THREAD

**Issue by jsfloresca** [Breeze/breeze.sharp#41]
Any time you attempt to run LoadNavigationProperty on an entity in the Modified EntityState then
 the following exception occurs:
Object reference not set to an instance of an object.

With the following stack trace:
StackTrace:
   at Breeze.Sharp.JsonEntityConverter.<>c__DisplayClass6_0.<ParseObject>b__0(KeyValuePair`2 kvp) in C:\GitHub\breeze.sharp\Breeze.Sharp\JsonEntityConverter.cs:line 258
  at Breeze.Sharp.Core.EnumerableFns.ForEach[T](IEnumerable`1 items, Action`1 action) in C:\GitHub\breeze.sharp\Breeze.Sharp\Core\EnumerableFns.cs:line 35
  at Breeze.Sharp.JsonEntityConverter.ParseObject(NodeContext nodeContext, EntityAspect targetAspect) in C:\GitHub\breeze.sharp\Breeze.Sharp\JsonEntityConverter.cs:line 201
  at Breeze.Sharp.JsonEntityConverter.PopulateEntity(NodeContext nodeContext, IEntity entity) in C:\GitHub\breeze.sharp\Breeze.Sharp\JsonEntityConverter.cs:line 188
  at Breeze.Sharp.JsonEntityConverter.CreateAndPopulate(NodeContext nodeContext) in C:\GitHub\breeze.sharp\Breeze.Sharp\JsonEntityConverter.cs:line 167
  at Breeze.Sharp.JsonEntityConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in C:\GitHub\breeze.sharp\Breeze.Sharp\JsonEntityConverter.cs:line 107
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, 

Object existingValue)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
  at Breeze.Sharp.EntityManager.<ExecuteQuery>d__42.MoveNext() in C:\GitHub\breeze.sharp\Breeze.Sharp\EntityManager.cs:line 305
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Breeze.Sharp.EntityManager.<ExecuteQuery>d__41.MoveNext() in C:\GitHub\breeze.sharp\Breeze.Sharp\EntityManager.cs:line 245
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Breeze.Sharp.EntityAspect.<LoadNavigationProperty>d__90.MoveNext() in C:\GitHub\breeze.sharp\Breeze.Sharp\EntityAspect.cs:line 1197
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at Breeze.Sharp.EntityAspect.<LoadNavigationProperty>d__89.MoveNext() in C:\GitHub\breeze.sharp\Breeze.Sharp\EntityAspect.cs:line 1192
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
  at Revo.Client.Infra.ModelExtensions.<CloneLegalTerms>d__35.MoveNext() in C:\Users\JFLORESCA\Documents\FINAL_PROJECT\revo\Revo.Client.Infra\ModelExtensions.cs:line 887
--- End of stack trace from previous location where exception was thrown ---

**Comment by Kapn** [comment]
Having this same issue occur when querying for an entity and 'Expanding'. The related entity that is grabbed by the expand has been modified and causes breeze to the error.

**Comment by steveschmitt** [comment]
Seems to be the same as #49.

**Comment by steveschmitt** [comment]
Fixed (I think) in v0.8.1
